name: default

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Full git history is needed to get a proper list of changed files within `super-linter`
        fetch-depth: 0
    - uses: github/super-linter/slim@v4
      env:
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_JAVASCRIPT_ES: true
        VALIDATE_EDITORCONFIG: true
        VALIDATE_YAML: true
        VALIDATE_BASH: true
        VALIDATE_BASH_EXEC: true
        FILTER_REGEX_EXCLUDE: CHANGELOG.md

  test:
    name: test
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - run: npm ci --no-production
    - run: npm test
