name: lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Full git history is needed to get a proper list of changed files
        # within `super-linter`
        fetch-depth: 0
    - uses: github/super-linter/slim@v4
      env:
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_JAVASCRIPT_ES: true
        VALIDATE_EDITORCONFIG: true
        VALIDATE_YAML: true
        VALIDATE_BASH: truea
        VALIDATE_BASH_EXEC: true
        FILTER_REGEX_EXCLUDE: CHANGELOG.md
