name: test

on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - run: npm ci --no-production
    - run: npm test
